WIP: add backend e2e test for service
apache/apisix-dashboard pull request #1128
Opened 2020-12-25 16:22 UTC by idbeta

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] E2E test
- [ ] New feature provided
- [ ] Improve performance

- Related issues

2021-01-06 14:03 UTC, idbeta commented
ping @nic-chen @membphis

2021-01-11 06:35 UTC, idbeta commented
ping @juzhiyuan Please remove the `Draft` tag of this PR.

2021-01-11 06:38 UTC, membphis requested changes

2021-01-11 06:38 UTC, membphis commented on api/test/e2e/service_test.go
> +	// hit routes
bad comment

2021-01-11 06:38 UTC, membphis commented on api/test/e2e/service_test.go
> +		fmt.Printf("server not responding %s", err.Error())
I think we should throw an error here

2021-01-11 06:47 UTC, idbeta commented on api/test/e2e/service_test.go
> +		fmt.Printf("server not responding %s", err.Error())
fixed.

2021-01-11 06:47 UTC, idbeta commented on api/test/e2e/service_test.go
> +	// hit routes
fixed.

2021-01-11 07:23 UTC, membphis approved these changes

2021-01-12 03:01 UTC, nic-chen approved these changes

2021-01-12 03:38 UTC, merged