Docs: Update PULL_REQUEST_TEMPLATE
apache/apisix-dashboard pull request #1244
Opened 2021-01-08 08:35 UTC by LiteSun

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

- Related issues

### New feature or improvement
- Describe the details and related test reports.
Add test case tips when fixing bugs

2021-01-08 10:46 UTC, juzhiyuan approved these changes

2021-01-08 15:32 UTC, juzhiyuan approved these changes

2021-01-08 15:33 UTC, liuxiran commented on .github/PULL_REQUEST_TEMPLATE
> +- Need to add the corresponding test cases if need.
```suggestion
- Please add the corresponding test cases if necessary.
```

2021-01-09 04:06 UTC, moonming requested changes
this desc should add after “bugfix” and “new feature”

2021-01-13 04:11 UTC, juzhiyuan commented
ping

2021-01-13 07:00 UTC, moonming approved these changes

2021-01-13 07:01 UTC, merged