Modify the upstream to use the new JSON patch package
apache/apisix-dashboard pull request #1395
Opened 2021-01-29 15:20 UTC by Jaycean

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#1392 
___
### Bugfix
- Description
I find that the jsonpatch(github.com/api7/go-jsonpatch) used by upstream and service when calling the patch method is still the old package,updated to github.com/evanphx/json-patch/v5

- How to fix?
Modify the upstream to use the new JSON patch package

2021-01-29 15:36 UTC, imjoey commented
@Jaycean In order to be a semantic pull request, please change the title to `fix: Modify the upstream to use the new JSON patch package` . Thanks.

2021-01-30 01:55 UTC, membphis approved these changes

2021-01-30 02:42 UTC, nic-chen commented on api/internal/handler/upstream/upstream.go
> -	"github.com/api7/go-jsonpatch"
seems we don't need `go-jsonpatch` any more. try `go mod tidy` to see if we could remove it？

2021-01-30 02:42 UTC, imjoey requested changes
@Jaycean  Since #1396 has been merged already, the Upstream is the only resource that's using `github.com/api7/go-jsonpatch`. So within this PR, we would better completely remove the dependency of `github.com/api7/go-jsonpatch`. 

Please rebase the master branch with the latest code and run `go mod tidy` for that. Thanks.

2021-01-30 02:53 UTC, Jaycean commented
> @Jaycean Since #1396 has been merged already, the Upstream is the only resource that's using `github.com/api7/go-jsonpatch`. So within this PR, we would better completely remove the dependency of `github.com/api7/go-jsonpatch`.
> 
> Please rebase the master branch with the latest code and run `go mod tidy` for that. Thanks.

Thanks for the reminder.done.

2021-01-30 03:15 UTC, imjoey commented
@nic-chen Backend E2E Test seems broken since this morning, prompted with the following error.  Could you please have a check? Thanks.

```
--- FAIL: TestBalancer_roundrobin_with_weight (0.66s)
    printer.go:54: PUT http://127.0.0.1:9000/apisix/admin/upstreams/1
    --- PASS: TestBalancer_roundrobin_with_weight/create_upstream_(roundrobin_with_same_weight) (0.06s)
    printer.go:54: PUT http://127.0.0.1:9000/apisix/admin/routes/1
    --- PASS: TestBalancer_roundrobin_with_weight/create_route_using_the_upstream_just_created (0.31s)
    base.go:150: 
        	Error Trace:	base.go:150
        	            				balancer_test.go:77
        	Error:      	Expected nil, but got: &url.Error{Op:"Get", URL:"http://127.0.0.1:9081/server_port", Err:(*net.OpError)(0xc0001b61e0)}
        	Test:       	TestBalancer_roundrobin_with_weight
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x8c8eed]
```

2021-01-30 06:21 UTC, tokers commented on api/internal/handler/upstream/upstream.go
> +	ID := input.ID
we should use variables started with letter in small case.

2021-01-30 06:21 UTC, tokers commented on api/internal/handler/upstream/upstream.go
> +	if err != nil {
Can be merged into:

```go
if err := json.Unmarshal(res, &upstream); err != nil {
```

2021-01-30 06:21 UTC, tokers commented on api/internal/handler/upstream/upstream.go
> +	if err != nil {
Can be merged into:

```go
if err := json.Unmarshal(res, &upstream); err != nil {
```

2021-01-30 06:21 UTC, tokers commented on api/internal/handler/upstream/upstream.go
> +
Why keep an empty line here?

2021-01-30 13:17 UTC, nic-chen commented
> @nic-chen Backend E2E Test seems broken since this morning, prompted with the following error. Could you please have a check? Thanks.
> 
> ```
> --- FAIL: TestBalancer_roundrobin_with_weight (0.66s)
>     printer.go:54: PUT http://127.0.0.1:9000/apisix/admin/upstreams/1
>     --- PASS: TestBalancer_roundrobin_with_weight/create_upstream_(roundrobin_with_same_weight) (0.06s)
>     printer.go:54: PUT http://127.0.0.1:9000/apisix/admin/routes/1
>     --- PASS: TestBalancer_roundrobin_with_weight/create_route_using_the_upstream_just_created (0.31s)
>     base.go:150: 
>         	Error Trace:	base.go:150
>         	            				balancer_test.go:77
>         	Error:      	Expected nil, but got: &url.Error{Op:"Get", URL:"http://127.0.0.1:9081/server_port", Err:(*net.OpError)(0xc0001b61e0)}
>         	Test:       	TestBalancer_roundrobin_with_weight
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x8c8eed]
> ```

@imjoey  @Jaycean  hi, have you found the reason of the failure of ci?

2021-01-30 13:21 UTC, Jaycean commented
> > @nic-chen Backend E2E Test seems broken since this morning, prompted with the following error. Could you please have a check? Thanks.
> > ```
> > --- FAIL: TestBalancer_roundrobin_with_weight (0.66s)
> >     printer.go:54: PUT http://127.0.0.1:9000/apisix/admin/upstreams/1
> >     --- PASS: TestBalancer_roundrobin_with_weight/create_upstream_(roundrobin_with_same_weight) (0.06s)
> >     printer.go:54: PUT http://127.0.0.1:9000/apisix/admin/routes/1
> >     --- PASS: TestBalancer_roundrobin_with_weight/create_route_using_the_upstream_just_created (0.31s)
> >     base.go:150: 
> >         	Error Trace:	base.go:150
> >         	            				balancer_test.go:77
> >         	Error:      	Expected nil, but got: &url.Error{Op:"Get", URL:"http://127.0.0.1:9081/server_port", Err:(*net.OpError)(0xc0001b61e0)}
> >         	Test:       	TestBalancer_roundrobin_with_weight
> > panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> > 	panic: runtime error: invalid memory address or nil pointer dereference
> > [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x8c8eed]
> > ```
> 
> @imjoey @Jaycean hi, have you found the reason of the failure of ci?
At present, we can only locate there
```
func BatchTestServerPort(t *testing.T, times int) map[string]int {
	url := APISIXSingleWorkerHost + "/server_port"
	req, err := http.NewRequest(http.MethodGet, url, nil)
	assert.Nil(t, err)

APISIXSingleWorkerHost = "http://127.0.0.1:9081"
```
This request`http://127.0.0.1:9081/server_port` 
A new route is created, which is exposed by apimix. It looks like a network problem here, but it can't be reproduced locally. No further problem is found.

2021-01-30 13:39 UTC, imjoey commented
> @imjoey @Jaycean hi, have you found the reason of the failure of ci?

@nic-chen  sorry, not get the solution yet. 😢

2021-01-30 15:56 UTC, nic-chen commented
@Jaycean @imjoey  
It seems to be affected by the last merged commit of APISIX

2021-01-31 01:50 UTC, Jaycean commented
> @Jaycean @imjoey
> It seems to be affected by the last merged commit of APISIX

Yes, just now I pulled the latest code of apisix, and the error has been reproduced locally.

2021-02-01 03:07 UTC, nic-chen commented
@Jaycean  CI passed

2021-02-01 03:13 UTC, imjoey commented
> @Jaycean CI passed

@nic-chen great thanks.

2021-02-01 03:21 UTC, Jaycean commented on api/internal/handler/upstream/upstream.go
> +	if err != nil {
done. Thks

2021-02-01 03:21 UTC, imjoey approved these changes
/lgtm

Thanks @Jaycean .

2021-02-01 03:23 UTC, Jaycean commented
> @Jaycean CI passed

Great Thks.

2021-02-01 03:26 UTC, merged