Update deploy-with-docker.md
apache/apisix-dashboard pull request #2472
Opened 2022-06-13 05:50 UTC by FangSen9000

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [*] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

它解决了[doc]仪表板docker实现使用优化issues[#2446](https://github.com/apache/apisix-dashboard/issues/2446)：
apisix-dashboard登录成功，然后访问apisix/admin/labels/route或apisix/admin/labels/consumer，遇到401未经授权的错误代码，这意味着仪表板授权的jwt令牌无效。

最后在社区的帮助下，发现原因不止1个仪表盘实例。
使用多实例，每个实例生成并持有一个jwt令牌，将导致验证冲突

因此，我们可以优化文档以强调仪表板实例数量不超过1，这与apisix本身的高可用性不同。

我已经在 Docker 相关文档中的适当位置添加了注释。

**Related issues**

fix/resolve [doc] 仪表板 Docker 实现使用优化 issues[#2446](https://github.com/apache/apisix-dashboard/issues/2446)

**Checklist:**

- [*] Did you explain what problem does this PR solve? Or what new features have been added?
- [*] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [*] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

2022-06-13 06:08 UTC, FangSen9000 commented
@Baoyuantop, I accidentally changed the file name before, but only changed the content this time.

2022-06-14 03:29 UTC, SkyeYoung requested changes
Pls refer to [other PRs](https://github.com/apache/apisix-dashboard/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) to edit your title.

2022-06-14 03:29 UTC, SkyeYoung commented on docs/en/latest/deploy-with-docker.md
> +2.  It is not recommended to use multiple instances at the same time.  When using multiple instances, each instance generates and holds a JWT token, which will lead to verification conflicts.
```suggestion
2.  It is not recommended to use multiple instances at the same time. When using multiple instances, each instance generates and holds a JWT token, which will lead to verification conflicts.
```

2022-06-14 03:33 UTC, SkyeYoung commented
Pls also revise the description of the PR in English to make it accurate and clear.

2022-06-28 02:51 UTC, kafkahz approved these changes

2022-07-04 01:26 UTC, Baoyuantop approved these changes

2022-07-04 03:02 UTC, juzhiyuan approved these changes

2022-07-04 03:03 UTC, SkyeYoung approved these changes

2022-07-04 03:04 UTC, merged