feat(route): make front-end adapt `route` v3 api modification
apache/apisix-dashboard pull request #2639
Opened 2022-10-14 04:42 UTC by tomtiao

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

It seems that `/labels/route` is missing in v3. This spawns Network Error notification which prevents tests from passing. Should I query all route data and collect the labels?

Tests of `route` fails due to:

- create process depends on other modules, like `upstream` which haven't been adapted yet
- missing apis in v3

I have modified some of the frontend code using the info in the Postman api docs. Tell me if I could do more.

### Code that block tests

- `batch-delete-route` test

  - `/labels/route` notification prevents cy from clicking the button
  - missing api

- `create-route-*` test

  - create process depends on `upstream`

- `data-loader-import` test

  - missing api

- `search-route` test

  - depends on create process

- `table-auto-jump-when-no-data` test

  - `/labels/route` notification prevents cy from clicking the button

**Related issues**

fix/resolve #2636 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

2022-10-17 05:47 UTC, SkyeYoung requested changes
Hi, pls fix these CI errors

2022-10-19 06:56 UTC, guoqqqi commented
Hello, @tomtiao Do you have any questions for the CI?

2022-10-19 07:00 UTC, guoqqqi commented
For features that are not yet supported, can we disable the corresponding test?

2022-10-20 13:21 UTC, tomtiao commented
> Hello, @tomtiao Do you have any questions for the CI?

I wonder if we could turn off the tests. 😂

2022-10-25 02:26 UTC, guoqqqi commented
> I wonder if we could turn off the tests. 😂

I think you can temporarily close the irrelevant tests, the relevant tests need to be fixed

2025-04-17 17:09 UTC, juzhiyuan commented
Thank you for your PR. We will create the new dashboard to resolve this issue. Refer to https://github.com/apache/apisix-dashboard/issues/2981

2025-04-17 17:09 UTC, closed without merging