test: add E2E testcase about #631
apache/apisix-dashboard pull request #875
Opened 2020-11-25 12:29 UTC by idbeta

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] E2E testcase
- [ ] New feature provided
- [ ] Improve performance

- Related issues

#872 #873

2020-11-25 12:30 UTC, juzhiyuan commented
Kindly add resolve keywords before issue number is needed.

2020-11-25 14:42 UTC, moonming requested changes

2020-11-25 14:42 UTC, moonming commented on api/test/e2e/route_e2e_remote_addr_rarescen_test.go
> + func TestRoute_add_with_invalid_remote_addr_rarescen(t *testing.T) {
what is “ratescen”？

2020-11-25 14:42 UTC, moonming commented on api/test/e2e/route_e2e_remote_addr_rarescen_test.go
> +			 ExpectStatus: http.StatusBadRequest,
still not test data plane. is this unit test or e2e？

2020-11-25 14:42 UTC, moonming commented on api/test/e2e/route_e2e_remote_addr_rarescen_test.go
> +			 Path:         "/apisix/admin/routes/r1",
this router is not created, why delete will return 200?

2020-11-25 15:30 UTC, membphis commented
we should use a useful title

2020-11-26 02:28 UTC, membphis commented
related issues: #872  #873 

one PR for one thing, so I think we have to close this PR

2020-11-26 02:28 UTC, closed without merging

2020-11-26 02:37 UTC, membphis commented
#872 : milestone 2.2
#873 : milestone 2.1.1

@idbeta you can add the test cases in the issue, it is a better way